version: "3"
services:

  mahrio-staticdb:
    build: .
    container_name: mahrio-staticdb
    env_file:
      - docker.env
    ports:
      - "6085:6085"
    restart: always

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080