version: "3"
services:

  mahrio-staticdb:
    build: .
    container_name: mahrio-staticdb
    env_file:
      - docker.env
    ports:
      - "6085:6085"
    restart: always
    depends_on:
      - mahrio-mysqldb

  mahrio-mysqldb:
    image: mysql:8
    container_name: mahrio-mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./mahrio-init-db.sql:/docker-entrypoint-initdb.d/mahrio-init-db.sql
      - data/.:docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
